service:
  type: NodePort
  port: 80

headerBackgroundColor: '#1e88e5'
image:
  imagePullPolicy: IfNotPresent
  repository: jmatiastw/unleash
  tag: 0.2.7
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: true
  host: unleash.chart.local
  path: /


posgresqlExistingSecret:
  name: unleash-superuser
  usernameKey: pg_su_username
  passwordKey: pg_su_password

postgresql:
  url: default
  database: default


replicaCount: 3
resources:
  limits:
    cpu: 64m
    memory: 64Mi
  requests:
    cpu: 128m
    memory: 128Mi

serviceMonitor:
  enabled: true