apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "unleash.fullname" . }}
  labels:
{{ include "unleash.labels" . | indent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}